version: 2.1

orbs:
  python: circleci/python@1.2
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: linting
          command: flake8

  build_push_to_docker_hub:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Build and push image to DockerHub
          command: |
            pip install --user --no-cache-dir -r requirements.txt
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          extra_build_args: "-t $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME"
          tag: 0.1.<< pipeline.number >>             
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: "latest"
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: "0.1.<< pipeline.number >>"

workflows:
  test_build_deploy:
    jobs:
      - build_and_test
      - build_push_to_docker_hub:
          requires:
            - build_and_test